# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad04c2d025bb424d5ef0e0b1c9dd53180e136648859d2426f82a1a03297f6720ea087b217acfb5bab4c7a635101f123f3b508ec2a9f80719bb5c3af1986c596a

test:
  secret_key_base: 7ac86c06cf0a4edeb8d472e593ed5a1aff82e6b311935842c855c0a04b8cae4643508b2ccad31a2610bb9031bf699368910d22c4fd01c2b74973cff3d68fe816

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
